# -*- coding: utf-8 -*-
"""Demo2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10JWYwedEaV6TneOw5b5H7zZgvgYwj7N4
"""


#Predecir el monto a comprar de acuerdo a las
# caracteristicas dadas(features)
#Utilizaremos algoritmos de regresion
#Import librerias
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
#Cargar el archivo ventas.csv
ventas = pd.read_csv("/content/sample_data/Libro1.csv");
#Fijar objetivo y variables independientes
objetivo = "monto"
# La variable va conter todas las columnas menor la columna monto
variables = ventas.drop(columns = ['monto']).columns
#print(variables)
#Generar el modelo -> El algoritmo a utilizar
modelolregresion = LinearRegression()
#Ajustar el modelo
#x todas las variables independientes, ventas es el objetivo
modelolregresion.fit(X=ventas[variables],y=ventas[objetivo])
#Conjunto de datos de reales y datos de predicion
#Realzacion de propiedad
ventas["ventas_pre"] =modelolregresion.predict(ventas[variables])
print(ventas["ventas_pre"])
pred = ventas[["monto","ventas_pre"]].head(40)
print(pred )
#Reañizar la predicion
prediccion = modelolregresion.predict([[40,0,1,1,2]])
print(" la persona compraria un monto equivalente a",prediccion)

