# -*- coding: utf-8 -*-
"""Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_wKIPOkOFFa4t0lrdKnoTKusQGOm1b9V
"""

#Importamos algoritmos de clasificacion
from sklearn.neighbors import KNeighborsClassifier
#Importar dataset iris(incluido en Python)
from sklearn.datasets import load_iris
#Importar funcion para proceso de seleccion de data
from sklearn.model_selection import train_test_split
#Guardamos el conjunto de datos Iris en una variable #Cargar dataset iris en una variable
iris = load_iris();
#Nota:la data se debe preparar (Transformar)
#Dividimos nuestros datos en "conjunto de entrenamiento" y "conjunto de prueba"
print(iris)
#Generar datos de train(Entrenamiento) y tes(Prueba) :Proceso para la preparacion de data
x_train, x_test,y_train, y_test = train_test_split(iris.data,iris.target)
#Implementar el modelo
knn = KNeighborsClassifier() #Declaramos nuestro modelo(Siempre se ajusta el modelo)
#Ajustamos a nuestro modelo
knn.fit(x_train,y_train)
#Probamos el modelo con el conocimiento que ha adquirido el modelo
#knn.score(x_test,y_test)
#Probar el modelo con data nueva (Data real)
knn.predict([[6.2, 3.4, 5.4, 2.3]])